#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stack_Overflow_CSV_Generator
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StackOverflow")]
	public partial class AnswersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPost(Post instance);
    partial void UpdatePost(Post instance);
    partial void DeletePost(Post instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public AnswersDataContext() : 
				base(global::Stack_Overflow_CSV_Generator.Properties.Settings.Default.StackOverflowConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AnswersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnswersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnswersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnswersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Post> Posts
		{
			get
			{
				return this.GetTable<Post>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="SO.Posts")]
	public partial class Post : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _AcceptedAnswerId;
		
		private System.Nullable<int> _AnswerCount;
		
		private string _Body;
		
		private System.Nullable<System.DateTime> _ClosedDate;
		
		private System.Nullable<int> _CommentCount;
		
		private System.Nullable<System.DateTime> _CommunityOwnedDate;
		
		private System.DateTime _CreationDate;
		
		private System.Nullable<int> _FavoriteCount;
		
		private System.DateTime _LastActivityDate;
		
		private System.Nullable<System.DateTime> _LastEditDate;
		
		private string _LastEditorDisplayName;
		
		private System.Nullable<int> _LastEditorUserId;
		
		private System.Nullable<int> _OwnerUserId;
		
		private System.Nullable<int> _ParentId;
		
		private int _PostTypeId;
		
		private int _Score;
		
		private string _Tags;
		
		private string _Title;
		
		private int _ViewCount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAcceptedAnswerIdChanging(System.Nullable<int> value);
    partial void OnAcceptedAnswerIdChanged();
    partial void OnAnswerCountChanging(System.Nullable<int> value);
    partial void OnAnswerCountChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnClosedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnClosedDateChanged();
    partial void OnCommentCountChanging(System.Nullable<int> value);
    partial void OnCommentCountChanged();
    partial void OnCommunityOwnedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCommunityOwnedDateChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    partial void OnFavoriteCountChanging(System.Nullable<int> value);
    partial void OnFavoriteCountChanged();
    partial void OnLastActivityDateChanging(System.DateTime value);
    partial void OnLastActivityDateChanged();
    partial void OnLastEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastEditDateChanged();
    partial void OnLastEditorDisplayNameChanging(string value);
    partial void OnLastEditorDisplayNameChanged();
    partial void OnLastEditorUserIdChanging(System.Nullable<int> value);
    partial void OnLastEditorUserIdChanged();
    partial void OnOwnerUserIdChanging(System.Nullable<int> value);
    partial void OnOwnerUserIdChanged();
    partial void OnParentIdChanging(System.Nullable<int> value);
    partial void OnParentIdChanged();
    partial void OnPostTypeIdChanging(int value);
    partial void OnPostTypeIdChanged();
    partial void OnScoreChanging(int value);
    partial void OnScoreChanged();
    partial void OnTagsChanging(string value);
    partial void OnTagsChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnViewCountChanging(int value);
    partial void OnViewCountChanged();
    #endregion
		
		public Post()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptedAnswerId", DbType="Int")]
		public System.Nullable<int> AcceptedAnswerId
		{
			get
			{
				return this._AcceptedAnswerId;
			}
			set
			{
				if ((this._AcceptedAnswerId != value))
				{
					this.OnAcceptedAnswerIdChanging(value);
					this.SendPropertyChanging();
					this._AcceptedAnswerId = value;
					this.SendPropertyChanged("AcceptedAnswerId");
					this.OnAcceptedAnswerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerCount", DbType="Int")]
		public System.Nullable<int> AnswerCount
		{
			get
			{
				return this._AnswerCount;
			}
			set
			{
				if ((this._AnswerCount != value))
				{
					this.OnAnswerCountChanging(value);
					this.SendPropertyChanging();
					this._AnswerCount = value;
					this.SendPropertyChanged("AnswerCount");
					this.OnAnswerCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClosedDate
		{
			get
			{
				return this._ClosedDate;
			}
			set
			{
				if ((this._ClosedDate != value))
				{
					this.OnClosedDateChanging(value);
					this.SendPropertyChanging();
					this._ClosedDate = value;
					this.SendPropertyChanged("ClosedDate");
					this.OnClosedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentCount", DbType="Int")]
		public System.Nullable<int> CommentCount
		{
			get
			{
				return this._CommentCount;
			}
			set
			{
				if ((this._CommentCount != value))
				{
					this.OnCommentCountChanging(value);
					this.SendPropertyChanging();
					this._CommentCount = value;
					this.SendPropertyChanged("CommentCount");
					this.OnCommentCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommunityOwnedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CommunityOwnedDate
		{
			get
			{
				return this._CommunityOwnedDate;
			}
			set
			{
				if ((this._CommunityOwnedDate != value))
				{
					this.OnCommunityOwnedDateChanging(value);
					this.SendPropertyChanging();
					this._CommunityOwnedDate = value;
					this.SendPropertyChanged("CommunityOwnedDate");
					this.OnCommunityOwnedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FavoriteCount", DbType="Int")]
		public System.Nullable<int> FavoriteCount
		{
			get
			{
				return this._FavoriteCount;
			}
			set
			{
				if ((this._FavoriteCount != value))
				{
					this.OnFavoriteCountChanging(value);
					this.SendPropertyChanging();
					this._FavoriteCount = value;
					this.SendPropertyChanged("FavoriteCount");
					this.OnFavoriteCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				if ((this._LastActivityDate != value))
				{
					this.OnLastActivityDateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDate = value;
					this.SendPropertyChanged("LastActivityDate");
					this.OnLastActivityDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastEditDate
		{
			get
			{
				return this._LastEditDate;
			}
			set
			{
				if ((this._LastEditDate != value))
				{
					this.OnLastEditDateChanging(value);
					this.SendPropertyChanging();
					this._LastEditDate = value;
					this.SendPropertyChanged("LastEditDate");
					this.OnLastEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEditorDisplayName", DbType="NVarChar(40)")]
		public string LastEditorDisplayName
		{
			get
			{
				return this._LastEditorDisplayName;
			}
			set
			{
				if ((this._LastEditorDisplayName != value))
				{
					this.OnLastEditorDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._LastEditorDisplayName = value;
					this.SendPropertyChanged("LastEditorDisplayName");
					this.OnLastEditorDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEditorUserId", DbType="Int")]
		public System.Nullable<int> LastEditorUserId
		{
			get
			{
				return this._LastEditorUserId;
			}
			set
			{
				if ((this._LastEditorUserId != value))
				{
					this.OnLastEditorUserIdChanging(value);
					this.SendPropertyChanging();
					this._LastEditorUserId = value;
					this.SendPropertyChanged("LastEditorUserId");
					this.OnLastEditorUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerUserId", DbType="Int")]
		public System.Nullable<int> OwnerUserId
		{
			get
			{
				return this._OwnerUserId;
			}
			set
			{
				if ((this._OwnerUserId != value))
				{
					this.OnOwnerUserIdChanging(value);
					this.SendPropertyChanging();
					this._OwnerUserId = value;
					this.SendPropertyChanged("OwnerUserId");
					this.OnOwnerUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int")]
		public System.Nullable<int> ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostTypeId", DbType="Int NOT NULL")]
		public int PostTypeId
		{
			get
			{
				return this._PostTypeId;
			}
			set
			{
				if ((this._PostTypeId != value))
				{
					this.OnPostTypeIdChanging(value);
					this.SendPropertyChanging();
					this._PostTypeId = value;
					this.SendPropertyChanged("PostTypeId");
					this.OnPostTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Int NOT NULL")]
		public int Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="NVarChar(150)")]
		public string Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this.OnTagsChanging(value);
					this.SendPropertyChanging();
					this._Tags = value;
					this.SendPropertyChanged("Tags");
					this.OnTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(250)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewCount", DbType="Int NOT NULL")]
		public int ViewCount
		{
			get
			{
				return this._ViewCount;
			}
			set
			{
				if ((this._ViewCount != value))
				{
					this.OnViewCountChanging(value);
					this.SendPropertyChanging();
					this._ViewCount = value;
					this.SendPropertyChanged("ViewCount");
					this.OnViewCountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="SO.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _AboutMe;
		
		private System.Nullable<int> _Age;
		
		private System.DateTime _CreationDate;
		
		private string _DisplayName;
		
		private int _DownVotes;
		
		private string _EmailHash;
		
		private System.DateTime _LastAccessDate;
		
		private string _Location;
		
		private int _Reputation;
		
		private int _UpVotes;
		
		private int _Views;
		
		private string _WebsiteUrl;
		
		private System.Nullable<int> _AccountId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAboutMeChanging(string value);
    partial void OnAboutMeChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnCreationDateChanging(System.DateTime value);
    partial void OnCreationDateChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnDownVotesChanging(int value);
    partial void OnDownVotesChanged();
    partial void OnEmailHashChanging(string value);
    partial void OnEmailHashChanged();
    partial void OnLastAccessDateChanging(System.DateTime value);
    partial void OnLastAccessDateChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnReputationChanging(int value);
    partial void OnReputationChanged();
    partial void OnUpVotesChanging(int value);
    partial void OnUpVotesChanged();
    partial void OnViewsChanging(int value);
    partial void OnViewsChanged();
    partial void OnWebsiteUrlChanging(string value);
    partial void OnWebsiteUrlChanged();
    partial void OnAccountIdChanging(System.Nullable<int> value);
    partial void OnAccountIdChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AboutMe", DbType="NVarChar(MAX)")]
		public string AboutMe
		{
			get
			{
				return this._AboutMe;
			}
			set
			{
				if ((this._AboutMe != value))
				{
					this.OnAboutMeChanging(value);
					this.SendPropertyChanging();
					this._AboutMe = value;
					this.SendPropertyChanged("AboutMe");
					this.OnAboutMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreationDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				if ((this._CreationDate != value))
				{
					this.OnCreationDateChanging(value);
					this.SendPropertyChanging();
					this._CreationDate = value;
					this.SendPropertyChanged("CreationDate");
					this.OnCreationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DownVotes", DbType="Int NOT NULL")]
		public int DownVotes
		{
			get
			{
				return this._DownVotes;
			}
			set
			{
				if ((this._DownVotes != value))
				{
					this.OnDownVotesChanging(value);
					this.SendPropertyChanging();
					this._DownVotes = value;
					this.SendPropertyChanged("DownVotes");
					this.OnDownVotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailHash", DbType="NVarChar(40)")]
		public string EmailHash
		{
			get
			{
				return this._EmailHash;
			}
			set
			{
				if ((this._EmailHash != value))
				{
					this.OnEmailHashChanging(value);
					this.SendPropertyChanging();
					this._EmailHash = value;
					this.SendPropertyChanged("EmailHash");
					this.OnEmailHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastAccessDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastAccessDate
		{
			get
			{
				return this._LastAccessDate;
			}
			set
			{
				if ((this._LastAccessDate != value))
				{
					this.OnLastAccessDateChanging(value);
					this.SendPropertyChanging();
					this._LastAccessDate = value;
					this.SendPropertyChanged("LastAccessDate");
					this.OnLastAccessDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(100)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reputation", DbType="Int NOT NULL")]
		public int Reputation
		{
			get
			{
				return this._Reputation;
			}
			set
			{
				if ((this._Reputation != value))
				{
					this.OnReputationChanging(value);
					this.SendPropertyChanging();
					this._Reputation = value;
					this.SendPropertyChanged("Reputation");
					this.OnReputationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpVotes", DbType="Int NOT NULL")]
		public int UpVotes
		{
			get
			{
				return this._UpVotes;
			}
			set
			{
				if ((this._UpVotes != value))
				{
					this.OnUpVotesChanging(value);
					this.SendPropertyChanging();
					this._UpVotes = value;
					this.SendPropertyChanged("UpVotes");
					this.OnUpVotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Views", DbType="Int NOT NULL")]
		public int Views
		{
			get
			{
				return this._Views;
			}
			set
			{
				if ((this._Views != value))
				{
					this.OnViewsChanging(value);
					this.SendPropertyChanging();
					this._Views = value;
					this.SendPropertyChanged("Views");
					this.OnViewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebsiteUrl", DbType="NVarChar(200)")]
		public string WebsiteUrl
		{
			get
			{
				return this._WebsiteUrl;
			}
			set
			{
				if ((this._WebsiteUrl != value))
				{
					this.OnWebsiteUrlChanging(value);
					this.SendPropertyChanging();
					this._WebsiteUrl = value;
					this.SendPropertyChanged("WebsiteUrl");
					this.OnWebsiteUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountId", DbType="Int")]
		public System.Nullable<int> AccountId
		{
			get
			{
				return this._AccountId;
			}
			set
			{
				if ((this._AccountId != value))
				{
					this.OnAccountIdChanging(value);
					this.SendPropertyChanging();
					this._AccountId = value;
					this.SendPropertyChanged("AccountId");
					this.OnAccountIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
